### PR TITLE
Update nl.csv

### PR DESCRIPTION
**Pull request by JimmyKer**
Added missing translations, and some minor changes for consistency.

### CODE REVIEW

**Review by zekth — APPROVED** [review]
lgtm

**Comment by stvnmbr1** [comment]
@JimmyKer 
where are you living, NL or BE? I don't use ph and such so was unsure for correct translations for those

**Comment by JimmyKer** [comment]
In Belgium!
For pH, I'm using Robo-tank from Rob, with a cheap Aliexpress sensor, works perfect but isn't the most valuable sensor. I’m dreaming of a KH measuring point. 👍

**Comment by stvnmbr1** [comment]
contact me on instagram, steviesyard, glad to see someone else in belgium is using reef-pi
there is a thread on r2r of someone who has gotten very close. thread died so not sure how far this is now.

**Comment by JimmyKer** [comment]
I'm not on instagram, but have started a thread here, so you can see some
pics:
https://www.zeewaterforum.info/forums/threads/red-sea-reefer-250-marco-rocks-robo-tank-reef-pi.192682/

By the way, you have some great pics on your insta!


Op zo 18 okt. 2020 om 18:56 schreef stvnmbr1 <notifications@github.com>:

**Pull request merged**
