### PR TITLE
Add smoke test

### PR DESCRIPTION
**Pull request by zekth**
fixes https://github.com/reef-pi/reef-pi/issues/1047

### CODE REVIEW

**Comment by zekth** [comment]
@ranjib ready to ship IMO. Not the best implementation but can be tackled as we move to github actions.

**Comment by ranjib** [comment]
sweet. The smoke test is broken currently :-(

**Comment by zekth** [comment]
weird it passes the CI :|
maybe npm swallows the error?

**Comment by ranjib** [comment]
@zekth looks like travis is passing even when the smoke test is failing.

**Comment by ranjib** [comment]
@zekth smoke test needs to run in devmode otherwise reef-pi will try to bind on port 80, and in CI it does not have sufficient permission to do so. Why the bash script is failing silently is a separate issue we have to diagnose

**Pull request closed without merging**
