### PR TITLE
Adding support for translations

### PR DESCRIPTION
**Pull request by zekth**
- Adding i18next to support translations
- Add csv to json support
- Updated documentation

### CODE REVIEW

**Comment by ranjib** [comment]
@zekth can we add french translation as part of this  ?

**Comment by ranjib** [comment]
👍

**Comment by zekth** [comment]
> @zekth can we add french translation as part of this ?

I can start working on it while implementing translations into the components

**Comment by ranjib** [comment]
@zekth ack. Let’s keep this pr open and not merge it till 2.0 release then

**Comment by ranjib** [comment]
Just for reference , here is the result of the poll from [reef2reef](https://www.reef2reef.com/threads/reef-pi-an-opensource-reef-tank-controller-based-on-raspberry-pi.289256)
screen shot 2018-11-11 at 8 27 30 am

**Comment by ranjib** [comment]
@zekth closing this.

**Pull request closed without merging**
