### PR TITLE
(bug)Don't register and remove zombie drivers

### PR DESCRIPTION
**Pull request by theatrus**
Scenario:

- Create ph_board driver with invalid I2C address
  - Call to register driver fails with error, not storing the driver in the drivers slice.
    - UI shows driver instance, as it was still written to the
      underlying store.

This fixes:

- Removing a driver which returned an error on registration from the
  store (consistency)
- Allowing the removal of a driver which is in the store but not in
  the loaded map (which could happen after the driver fails to
  register due to removed hardware on reload)
- Closing the driver upon removal.

### CODE REVIEW

**Comment by ranjib** [comment]
@theatrus let’s juts move the store.create call after register, instead of creating first and then deleting the driver if it’s failed to register . We have to remember that this will mean we won’t be able to add driver that can not be registered due to some reason

**Comment by theatrus** [comment]
@ranjib Sounds good - forgot ID assignment was not required for register

**Comment by theatrus** [comment]
@ranjib Actually, no go:

https://github.com/reef-pi/reef-pi/blob/master/controller/drivers/factories.go#L107

We need the ID to register, which means we need to have created the object

**Comment by theatrus** [comment]
@ranjib Feel free to merge when you can :-)

**Pull request merged**
