### PR TITLE
 First cut of a German translation

### PR DESCRIPTION
**Pull request by schwabix-1311**
This is the main UI, including additions and fixes in .jsx affecting other languages.
There are still lots of validation messages literally in the *schema* files.

On top of this, there's one suggested feature change: 
on temperature chart I changed the legend box to show usage percentages for 
heater/chjiller instead of seconds. (This might be nicer for the data series in the
chart itself too.) The 100% reference is a constant of 3600, which would be wrong for 
different time scales. Don't where to get this value dynamically.

This is my first bigger commit to this project, I therefore don't know whether go.mod, 
go.sum and package-lock.json should be included. I did not actively modify them.

### CODE REVIEW

**Comment by ranjib** [comment]
@schwabix-1311 the changes look very good to me. But let's break them apart in smaller bits to reduce the risk and ease testing.
Include everything that's not git excluded, including go.mod, go.sum, packaga-lock.json files.
Let's break down the changeset to individual bits. 
- separate german translation from the rest, either use this PR, or create a new one.
-  jest fixes could be a separate PR
- let's discuss the heater legend changes in a separate issue. I'm not sure if I understand the reasoning behind % e sense. But worth discussing this,

**Comment by schwabix-1311** [comment]
Ok, I'll separate the legend changes to allow a discussion in the new PR (and jest changes were just a fix for my additions). I'll also explain my intent in a new issue.

Separation of German vs. the other languages is a question of workflow. I usually prefer to have each commit / PR result in a complete and consistent overall system, such that later on you can revert to any commit.
That said, the German translation is a bit more than just an update of the string tables. It includes and depends on many code changes. Likewise the other languages' strings require the code changes to make them work.

Of course, this is your project, if you prefer a commit granularity that's more focused on smaller reviewable chunks, this is OK with me. Would you like to have speparate PRs for just code and one for each language, or one for code & German/English and another one for ROW?

And as a side note, I grew up with VCS/PVCS/SourceSafe/Perforce. Lately touched git just a little. Pretty different terminology and workflows. I may take unusual bends to achieve above restructuring. Please be patient ;-)

**Comment by zekth** [comment]
> Of course, this is your project, if you prefer a commit granularity that's more focused on smaller reviewable chunks, this is OK with me. Would you like to have speparate PRs for just code and one for each language, or one for code & German/English and another one for ROW?

As long as PR are feature / fix scoped it's fine. In this case i'd recommend to create one for the DE translation itself and one other for the fix regarding mappings and such. Makes everything clearer in the history and also for the review process

**Comment by ranjib** [comment]
@schwabix-1311 can you rebase against master?

**Comment by schwabix-1311** [comment]
PR 1503 includes all relevant changes, thus obsoleting this one. Closing.

**Pull request closed without merging**
