### PR TITLE
Validations

### PR DESCRIPTION
**Pull request by schwabix-1311**
Issue #1518.  NOT YET complete.
However, before I invest too much time, I'd want to get feedback whether this direction gets your support.

Each commit covers validation of one main page. This includes the changes to translation in en/de, other languages are beyond my skills.
Confirmations for delete operations, plus calibration dialogs are also included.

And one fix I could not resist:  on Drivers page, the 'rpi' was presented differently, this is addressed.

There's about the same amount, may be a bit more in the pipeline.

### CODE REVIEW

**Comment by schwabix-1311** [comment]
Why does jest complain?
The offending lines are all the same pattern, mimicking string interpolation in combination with  strings from i18next:
 `confirm(i18n.t('ato:title_delete').replace('${name}', probe.name), { description: message })`
with:
`ato:title_delete,"Delete ${name} ?"`
Do you have a better solution?

**Comment by schwabix-1311** [comment]
Well, the pseudo string interpolation using  '$[name]' does work and is accepted by jest, while the form '${name}' is rejected.
The later is closer to real interpolation, therefore I'd prefer this.
What's your preference?

**Comment by ranjib** [comment]
@schwabix-1311 can u isolate the changes, else it will harder for me to review. I think , some of the changes contains unnecessary line swaps, not sure why. Please raise the translations, delete validation and typo fixes as separate PRs. 
thank you

**Comment by schwabix-1311** [comment]
The line swaps allowed me to use a diff tool between two main pages with similar structure & features (I don't remember which two these were) and thus to understand why they reacted differently.  The swaps can be undone, but honestly,  if I try to get this cleanly into git I will screw things up, almost guaranteed.

**Pull request closed without merging**
