### PR TITLE
sk.csv

### PR DESCRIPTION
**Pull request by loksiklubos**
sk.csv

### CODE REVIEW

**Review by loksiklubos — COMMENTED** [review]
sk.csv

**Comment by ranjib** [comment]
Thank you for the contribution. What language is this?

**Comment by ranjib** [comment]
Slovak it is :-) . 
Ďakujem

**Comment by loksiklubos** [comment]
Slovak translation / Slovak Republic



          S pozdravom






<http://www.maslen.sk/>



*Ľuboš Lokšík*

*loksik.lubos@gmail.com <loksik.lubos@gmail.com>*







ne 24. 1. 2021 o 5:45 Ranjib Dey <notifications@github.com> napísal(a):

**Pull request merged**
