### PR TITLE
Add github ci build

### PR DESCRIPTION
**Pull request by zekth**
This aims to move the CI to Github

### CODE REVIEW

**Comment by zekth** [comment]
Ready to ship.
5:40s in travis vs 3:40s in Github ci

Also is the gem dependency still revelant? i don't know the goal of it.

**Comment by zekth** [comment]
@ranjib any review?

**Comment by ranjib** [comment]
@zekth the build is passing even if ./build/ci.sh script is failing on " goimports command not found"

**Comment by zekth** [comment]
> @zekth the build is passing even if ./build/ci.sh script is failing on " goimports command not found"

`if [ -n "$(goimports -local github.com/reef-pi/reef-pi -d ./controller | tee /dev/stderr)" ]; then`

Maybe it's swallowed here. Gotta dig into.

**Comment by ranjib** [comment]
@zekth are you still planning to work on this? If not lets close it and move on

**Comment by zekth** [comment]
I think for now because you re happy with travis we can close it

**Pull request closed without merging**
